### ISSUE TITLE
[BUG] Unknown type `DQ_robotics::SOMETHING`

### ISSUE THREAD

**Issue by mmmarinho** [dqrobotics/python#49]
**Bug description**

This is an issue to help me start tracking this bug as I haven't been able to fully identify when it happens.

**To Reproduce**

- Have a version of `dqrobotics` Python3 installed, let's call it XXX.
- Try to make that work with another pybind11 compiled with a (slightly different) version of `dqrobotics` CPP (or environment), let's call it YYY.

**Problem**

All sorts of bugs involving `Unknown type` and the `DQ_robotics` namespace, when XXX is different from YYY.

**Solution**

The Python3 version of `dqrobotics` can be fixed by being compiled locally. This mismatch might be due to the environment used to compile with GitHub actions, that might need adjustments (I'm looking at you, GCC version). 

Remember to source your `venv` if you're using one
```console
python3 -m pip uninstall dqrobotics
git clone https://github.com/dqrobotics/python.git dqrobotics_python --recursive
python3 -m pip install wheel scipy quadprog
python3 -m pip install ./dqrobotics_python 

cd dqrobotics_python/tests
python DQ_test.py
python DQ_Kinematics_test.py
python cpp_issues.py
python python_issues.py
cd ..
```

**Concrete error examples**

@qlin960618 

```console
>>> from adaptive_control_example import *
Traceback (most recent call last):
[...]
    from ._core import *
ImportError: generic_type: type "Example_SerialManipulatorEDH" referenced unknown base type "DQ_robotics::DQ_SerialManipulator"
```

**Comment by bvadorno** [comment]
@mmmarinho, any new developments on this?

**Comment by mmmarinho** [comment]
@bvadorno 

The major cause for this was originally addressed in https://github.com/dqrobotics/python/issues/44. That fix should solve most occurrences caused by our choices and I also mention how to maintain it for future versions.

However, there are near infinite situations in which this import error can happen and most of them related to complex interactions with the user environment and advanced use of the library with custom Python bindings and custom C++ code. At this stage, I don't have enough information to propose a universal fix (beyond compiling locally as described above), but I'm sure this issue will resurface for advanced users. 

When it does resurface, I'd prefer to center all the related discussion in this issue instead of having it spread between smaller, seemingly disjoint issues, when in fact they have the same underlying cause.

**Comment by qlin960618** [comment]
Hi @mmmarinho, 

Thanks in advance for your assistance!
For some reason I am not sure why this problem is resurfacing again... specificly in something that I am doing.

Following back to the original **concrete example** in [tro2022_adaptivecontrol](https://github.com/mmmarinho/tro2022_adaptivecontrol)

```shell
./test_python_wrapper.sh 
```
OUTPUT 
```
  File "???/site-packages/marinholab/papers/tro2022/adaptive_control/__init__.py", line 3, in <module>
    from marinholab.papers.tro2022.adaptive_control._core import *
ImportError: generic_type: type "Example_SerialManipulatorEDH" referenced unknown base type "DQ_robotics::DQ_SerialManipulator"
```
Something else I tried changing in test_python_wrapper.sh 
```shell
#python3 -m pip install dqrobotics --pre
python3 -m pip install ./python_wrapper/dqrobotics_python
```
in the original script using system env or venv by adding 
```
python3.12 -m venv test_env 
source test_env/bin/activate
```
Is there any pointer in how I can solve this issue? I notice there are several commit there recently attempting to solve the same problem?

this is my current setup for reference
MacOS: Sequoia 15.5 (24F74)
Python version: Python 3.12.11 
```shell
whereis python3.12
python3.12: /opt/homebrew/bin/python3.12 /opt/homebrew/share/man/man1/python3.12.1
```

**Comment by mmmarinho** [comment]
Hi @qlin960618,

Whenever you have this problem it’s always because the packages you have installed are out of sync. Sometimes a problem on your end, sometimes on my end. 

Could you please start by uninstalling the packages (possibly cleaning the cache). Check at PyPi if you really have the latest ones. 
https://pypi.org/project/dqrobotics/#history

Then reinstall starting from `DQRobotics` with `—pre`?

If you’re sure you have the latest packages then I’ll check it on my end.

**Comment by qlin960618** [comment]
Hi @mmmarinho 
I can confirm that I have clear the cache with 
```shell
python3.12 -m pip cache purge
```
aside from that, I am still getting the same error. 
with 
```python3 -m pip install dqrobotics --pre```
Which I am getting *25.4.0a7* for the latest
or
```python3 -m pip install ./python_wrapper/dqrobotics_python```


The other recent things I change is upgrading my MacOS, but I have no way of reverting that I think...

**Comment by mmmarinho** [comment]
@qlin960618 

What’s your version of this package?
https://pypi.org/project/marinholab-papers-tro2022-adaptivecontrol/#history

**Comment by mmmarinho** [comment]
@qlin960618 

This worked for me in MacOS just now

Replace the `python3.11` with whatever python you want to use. Please use `3.10` and above.

```
cd ~
mkdir testissue
cd testissue
python3.11 -m venv venv
source venv/bin/activate
python -m pip install -U pip
python -m pip install dqrobotics --pre
python -m pip install marinholab-papers-tro2022-adaptivecontrol
```

Then try

```
python
Python 3.11.12 (main, Apr  8 2025, 14:15:29) [Clang 17.0.0 (clang-1700.0.13.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from marinholab.papers.tro2022.adaptive_control import *
```

It imported with no errors for me.

**Comment by qlin960618** [comment]
Hi @mmmarinho 

I can confirm pulling the package from pypi works without problem here....

So issue only exist if I try compiling locally???? Not sure what is the problem here. 

I ve replace the test_python_wrapper.sh with the following
```shell
python3.12 -m venv test_venv
source test_venv/bin/activate

#python3 -m pip config set global.break-system-packages true
python3.12 -m pip install --upgrade pip
python3.12 -m pip install setuptools wheel setuptools-git-versioning

#python3.12 -m pip install dqrobotics --pre
python3.12 -m pip install ./python_wrapper/dqrobotics_python/.
python3.12 -m pip install ./python_wrapper
#python ./python_wrapper/setup.py build_ext --verbose

cat adaptive_control_import_eval.py
python3.12 adaptive_control_import_eval.py
```

just for reference this is my gcc version
```shell
 gcc --version
Apple clang version 17.0.0 (clang-1700.0.13.5)
Target: arm64-apple-darwin24.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
and cmake 
```shell
cmake version 4.0.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
I have also tried reinstall cmake with ```brew reinstall``` and nuking the Xcode into trash with still no dice....

**Comment by mmmarinho** [comment]
Hi @qlin960618,

Thank you for the enlivened comment.

I suppose that with the local compilation it does not work for you yet. This is one way that should work.
(The train's internet isn't the best so I'm 90% sure this works)

```
cd ~
mkdir testissueagain
cd testissueagain

git clone https://github.com/mmmarinho/tro2022_adaptivecontrol.git --recursive
cd tro2022_adaptivecontrol.git

python3.12 -m venv test_venv
source test_venv/bin/activate

python -m pip install --upgrade pip
python -m pip install setuptools wheel setuptools-git-versioning

python -m pip install ./python_wrapper/dqrobotics_python
python -m pip install ./python_wrapper
```

**Comment by qlin960618** [comment]
Hi @mmmarinho, 

thanks again for any assistance.
Sorry, I am not seeing entirly what is the main difference. but I have replace `python3.12` with `python` just in case....
However, this is the output I am getting still.
can i double check with yours if the version etc is the same? some package is breaking something somewhere... I think I am just not noticing...

```shell
Requirement already satisfied: pip in /Users/quentinlin/Github/testissueagain/test_venv/lib/python3.12/site-packages (25.1.1)
Collecting setuptools
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Collecting wheel
  Using cached wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Collecting setuptools-git-versioning
  Using cached setuptools_git_versioning-2.1.0-py3-none-any.whl.metadata (6.1 kB)
Collecting packaging (from setuptools-git-versioning)
  Using cached packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Using cached setuptools-80.9.0-py3-none-any.whl (1.2 MB)
Using cached wheel-0.45.1-py3-none-any.whl (72 kB)
Using cached setuptools_git_versioning-2.1.0-py3-none-any.whl (10 kB)
Using cached packaging-25.0-py3-none-any.whl (66 kB)
Installing collected packages: wheel, setuptools, packaging, setuptools-git-versioning
Successfully installed packaging-25.0 setuptools-80.9.0 setuptools-git-versioning-2.1.0 wheel-0.45.1
Processing ./python_wrapper/dqrobotics_python
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from dqrobotics==25.4.0a7)
  Using cached numpy-2.3.0-cp312-cp312-macosx_14_0_arm64.whl.metadata (62 kB)
Using cached numpy-2.3.0-cp312-cp312-macosx_14_0_arm64.whl (5.1 MB)
Building wheels for collected packages: dqrobotics
  Building wheel for dqrobotics (pyproject.toml) ... done
  Created wheel for dqrobotics: filename=dqrobotics-25.4.0a7-cp312-cp312-macosx_15_0_arm64.whl size=399833 sha256=f74a5067fb259d4f2a342601bcf1ddb971638ad0e0b76204f3315df25171e1b6
  Stored in directory: /private/var/folders/9c/x357m5_x4jx6yvf4ylpyrpcm0000gn/T/pip-ephem-wheel-cache-fs1e63zp/wheels/50/9e/2f/90508651a477f4d08ef2ef0761181e632377f7c8e0c598bd2c
Successfully built dqrobotics
Installing collected packages: numpy, dqrobotics
Successfully installed dqrobotics-25.4.0a7 numpy-2.3.0
Processing ./python_wrapper
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: dqrobotics>=23.4.0a49 in /Users/quentinlin/Github/testissueagain/test_venv/lib/python3.12/site-packages (from marinholab-papers-tro2022-adaptivecontrol==25.6.0.25) (25.4.0a7)
Collecting dqrobotics-interface-coppeliasim-zmq (from marinholab-papers-tro2022-adaptivecontrol==25.6.0.25)
  Using cached dqrobotics_interface_coppeliasim_zmq-25.4.0a17-cp312-cp312-macosx_14_0_arm64.whl.metadata (1.2 kB)
Requirement already satisfied: numpy in /Users/quentinlin/Github/testissueagain/test_venv/lib/python3.12/site-packages (from dqrobotics>=23.4.0a49->marinholab-papers-tro2022-adaptivecontrol==25.6.0.25) (2.3.0)
Using cached dqrobotics_interface_coppeliasim_zmq-25.4.0a17-cp312-cp312-macosx_14_0_arm64.whl (414 kB)
Building wheels for collected packages: marinholab-papers-tro2022-adaptivecontrol
  Building wheel for marinholab-papers-tro2022-adaptivecontrol (pyproject.toml) ... done
  Created wheel for marinholab-papers-tro2022-adaptivecontrol: filename=marinholab_papers_tro2022_adaptivecontrol-25.6.0.25-cp312-cp312-macosx_15_0_arm64.whl size=336751 sha256=f4e1f5b5885215db88273e29282ac84290a5cf0726388b445d31c5575a0d4d1c
  Stored in directory: /private/var/folders/9c/x357m5_x4jx6yvf4ylpyrpcm0000gn/T/pip-ephem-wheel-cache-uhe9zzy_/wheels/31/59/ab/6c22e019abbb999482fea56b8bed065430af0bda900f3786c0
Successfully built marinholab-papers-tro2022-adaptivecontrol
Installing collected packages: dqrobotics-interface-coppeliasim-zmq, marinholab-papers-tro2022-adaptivecontrol
Successfully installed dqrobotics-interface-coppeliasim-zmq-25.4.0a17 marinholab-papers-tro2022-adaptivecontrol-25.6.0.25
((test_venv) ) ➜  tro2022_adaptivecontrol git:(master) ✗ ls                                                                git:(master|✚1…2 
adaptive_control_import_eval.py          include                                  README.md                                test_python_wrapper.sh
CMakeLists.txt                           LICENSE                                  src                                      test_venv
Example.md                               python_wrapper                           submodules                               TRO2022_MarinhoAdorno_ReferenceScene.ttt
((test_venv) ) ➜  tro2022_adaptivecontrol git:(master) ✗ python adaptive_control_import_eval.py                            git:(master|✚1…2 
Traceback (most recent call last):
  File "/Users/quentinlin/Github/testissueagain/tro2022_adaptivecontrol/adaptive_control_import_eval.py", line 4, in <module>
    from marinholab.papers.tro2022.adaptive_control import *
  File "/Users/quentinlin/Github/testissueagain/test_venv/lib/python3.12/site-packages/marinholab/papers/tro2022/adaptive_control/__init__.py", line 3, in <module>
    from marinholab.papers.tro2022.adaptive_control._core import *
ImportError: generic_type: type "Example_SerialManipulatorEDH" referenced unknown base type "DQ_robotics::DQ_SerialManipulator"
```

**Comment by mmmarinho** [comment]
Hi @qlin960618 

The main difference is 

```
git clone https://github.com/mmmarinho/tro2022_adaptivecontrol.git --recursive
```

so that you get a fresh clone with the latest code. This is a way to mimic what's done in the continuous integration that creates the packages for PyPI.

**Comment by qlin960618** [comment]
Hi @mmmarinho 

thanks! ic...
for the run that I did, i did  use `--recursive`. So maybe that is not the cause?

**Comment by mmmarinho** [comment]
Hi @qlin960618,

My hypothesis is that your repository is not the latest. The submodules are frequently not in the version they are supposed to be. So my instructions were to re-clone a fresh copy as described, then it should work. 

Is there a pressing reason why not to use the PyPI version in your case?

**Comment by qlin960618** [comment]
Hi @mmmarinho 
Ic... in this case i will see what i can do...

The original question is not actually about the specific repo. Just that i have a piece of code that i am building is also having similar issue when importing module from dqrobotics. Wondering if there is recent changes here bring about this since **tro2022_adaptivecontrol** was one example i remember to b e the same structure.

best regard!

**Comment by mmmarinho** [comment]
Right, thanks for letting me know @qlin960618.

If everything is built in the same system in an organized way it will always work. It will be more difficult if you try to have some packages locally built and some from PyPI, for instance. 

I’m closing this issue because it’s not a problem in this repo but if you need a hand I can help you through other channels.
